# Generated by Django 6.0.3 on 2026-04-02 01:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('barber', '0001_initial'),
        ('barbershop', '0001_initial'),
        ('payment_method', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_charged', models.DecimalField(decimal_places=2, help_text='Puede diferir del precio base del servicio (descuentos, etc.)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio cobrado')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre cliente')),
                ('service_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Por defecto la hora actual. Puede editarse si se registro tarde.', verbose_name='Fecha y hora del servicio')),
                ('status', models.CharField(choices=[('completado', 'Completado'), ('cancelado', 'Cancelado'), ('pendiente_pago', 'Pendiente de Pago')], default='completado', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_record', to='appointment.appointment')),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='barber.barber')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='barbershop.barbershop')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='payment_method.paymentmethod')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
            ],
            options={
                'verbose_name': 'Registro de Servicio',
                'verbose_name_plural': 'Registros de Servicio',
                'ordering': ['-service_datetime'],
                'indexes': [models.Index(fields=['barbershop', 'service_datetime'], name='service_rec_barbers_c98f46_idx'), models.Index(fields=['barber', 'service_datetime'], name='service_rec_barber__f027eb_idx')],
            },
        ),
    ]
