# Generated by Django 6.0.3 on 2026-04-30 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0001_initial'),
        ('service_record', '0003_alter_servicerecord_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecordpaymentsplit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto pagado con este método'),
        ),
        migrations.AlterUniqueTogether(
            name='servicerecordpaymentsplit',
            unique_together={('service_record', 'payment_method')},
        ),
    ]
