# Generated by Django 6.0.3 on 2026-04-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbershop',
            options={'ordering': ['name'], 'verbose_name': 'Barbería', 'verbose_name_plural': 'Barberías'},
        ),
    ]
