# Generated by Django 6.0.3 on 2026-04-02 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, verbose_name='Codigo interno')),
                ('is_cash', models.BooleanField(default=False, help_text='True si es efectivo fisico (para el conteo de caja)', verbose_name='Es efectivo fisico')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='barbershop.barbershop')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'ordering': ['name'],
                'unique_together': {('barbershop', 'code')},
            },
        ),
    ]
