# Generated by Django 6.0.3 on 2026-04-02 01:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barber', '0001_initial'),
        ('barbershop', '0001_initial'),
        ('payment_method', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto pagado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago de Vale',
                'verbose_name_plural': 'Pagos de Vales',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto del vale')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto pagado hasta ahora')),
                ('detail', models.TextField(blank=True, verbose_name='Detalle / motivo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcialmente_pagado', 'Parcialmente Pagado'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='barber.barber')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='barbershop.barbershop')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_given', to='payment_method.paymentmethod', verbose_name='Metodo con que se entrego')),
            ],
            options={
                'verbose_name': 'Vale',
                'verbose_name_plural': 'Vales',
                'ordering': ['-created_at'],
            },
        ),
    ]
