# Generated by Django 6.0.3 on 2026-04-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advance', '0001_initial'),
        ('barber', '0001_initial'),
        ('barbershop', '0001_initial'),
        ('payment_method', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_registered', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='advance.advance', verbose_name='Vale al que aplica'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='barber.barber'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='barbershop.barbershop'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments_received', to='payment_method.paymentmethod', verbose_name='Metodo con que se recibio'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments_registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
