# Generated by Django 6.0.3 on 2026-04-30 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha del pago'),
        ),
    ]
