# Generated by Django 6.0.3 on 2026-05-06 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0003_b2_model_fixes'),
        ('barber', '0004_b2_model_fixes'),
        ('barbershop', '0002_b2_model_fixes'),
        ('payment_method', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['barbershop', 'status'], name='advance_shop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['barbershop', 'created_at'], name='advance_shop_created_idx'),
        ),
    ]
