# Generated by Django 6.0.3 on 2026-05-07 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0004_advance_advance_shop_status_idx_and_more'),
        ('barber', '0005_barber_barber_shop_active_idx_and_more'),
        ('barbershop', '0002_b2_model_fixes'),
        ('payment_method', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['barbershop', 'payment_date'], name='advpay_shop_date_idx'),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['barbershop', 'barber'], name='advpay_shop_barber_idx'),
        ),
    ]
