# Generated by Django 6.0.3 on 2026-04-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
