# Generated by Django 6.0.3 on 2026-04-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_add_specialty_to_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
