# Generated by Django 6.0.3 on 2026-04-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_add_photo_url_to_barber'),
        ('barbershop', '0002_b2_model_fixes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barber',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='barber',
            constraint=models.UniqueConstraint(condition=models.Q(('document_id__gt', '')), fields=('barbershop', 'document_id'), name='unique_barber_document_per_barbershop'),
        ),
    ]
