# Generated by Django 6.0.3 on 2026-05-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_b2_model_fixes'),
        ('barbershop', '0002_b2_model_fixes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='barber',
            index=models.Index(fields=['barbershop', 'active'], name='barber_shop_active_idx'),
        ),
        migrations.AddIndex(
            model_name='barberdailyactive',
            index=models.Index(fields=['barbershop', 'work_date', 'is_active'], name='bda_shop_date_active_idx'),
        ),
    ]
