# Generated by Django 6.0.3 on 2026-04-02 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barber', '0001_initial'),
        ('barbershop', '0001_initial'),
        ('payment_method', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Fecha del cierre')),
                ('total_services_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total en servicios')),
                ('total_products_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total en productos vendidos')),
                ('total_advance_payments', models.DecimalField(decimal_places=2, default=0, help_text='Dinero EXTRA que entra a caja cuando un barbero paga su vale', max_digits=12, verbose_name='Total ingresado por pago de vales')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total en gastos')),
                ('total_advances_given', models.DecimalField(decimal_places=2, default=0, help_text='Dinero que SALIO de caja en vales. NO descuenta comisiones.', max_digits=12, verbose_name='Total en vales entregados')),
                ('barber_commission_total', models.DecimalField(decimal_places=2, default=0, help_text='Suma de comisiones de todos los barberos del dia. NO se ven afectadas por vales.', max_digits=12, verbose_name='Total comisiones barberos')),
                ('barbershop_profit', models.DecimalField(decimal_places=2, default=0, help_text='(Servicios + Productos + PagosVale) - Gastos - Vales - Comisiones', max_digits=12, verbose_name='Ganancia neta de la barberia')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('guardado', 'Guardado'), ('confirmado', 'Confirmado')], default='borrador', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notas del cierre')),
                ('data_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='barbershop.barbershop')),
            ],
            options={
                'verbose_name': 'Reporte Diario',
                'verbose_name_plural': 'Reportes Diarios',
                'ordering': ['-report_date'],
                'unique_together': {('barbershop', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='BarberDailyCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_date', models.DateField(verbose_name='Fecha')),
                ('services_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total servicios del barbero')),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% comision')),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='services_total * commission_percentage / 100. Los vales NO se descuentan aqui.', max_digits=12, verbose_name='Comision ganada')),
                ('pending_advances_total', models.DecimalField(decimal_places=2, default=0, help_text='Suma de vales sin pagar del barbero. Solo informativo, NO se descuenta de la comision.', max_digits=12, verbose_name='Vales pendientes del barbero (informativo)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_commissions', to='barber.barber')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbershop')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_commissions', to='report.dailyreport')),
            ],
            options={
                'verbose_name': 'Comision Diaria Barbero',
                'verbose_name_plural': 'Comisiones Diarias Barberos',
                'ordering': ['-commission_date'],
                'unique_together': {('barber', 'commission_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyReportPaymentBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Servicios cobrados con este metodo')),
                ('products_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Productos vendidos con este metodo')),
                ('advance_payments_amount', models.DecimalField(decimal_places=2, default=0, help_text='Dinero EXTRA que entro a caja por pago de vale', max_digits=12, verbose_name='Pagos de vales recibidos con este metodo')),
                ('expenses_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos pagados con este metodo')),
                ('advances_given_amount', models.DecimalField(decimal_places=2, default=0, help_text='Dinero que salio de caja en vales con este metodo', max_digits=12, verbose_name='Vales entregados con este metodo')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_breakdown', to='report.dailyreport')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_breakdowns', to='payment_method.paymentmethod')),
            ],
            options={
                'verbose_name': 'Desglose de Pago Diario',
                'verbose_name_plural': 'Desgloses de Pago Diarios',
                'unique_together': {('daily_report', 'payment_method')},
            },
        ),
    ]
