# Generated by Django 6.0.3 on 2026-04-03 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_add_specialty_to_barber'),
        ('product', '0002_productsale_sale_date_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sales', to='barber.barber', verbose_name='Vendedor de productos (Opcional)'),
        ),
    ]
