# Generated by Django 6.0.3 on 2026-04-29 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0001_initial'),
        ('product', '0004_mixed_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sales', to='payment_method.paymentmethod'),
        ),
    ]
