# Generated by Django 6.0.3 on 2026-04-30 21:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0001_initial'),
        ('product', '0005_alter_productsale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Fecha real de la venta', verbose_name='Fecha de la venta'),
        ),
        migrations.AlterField(
            model_name='productsalepaymentsplit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto pagado con este método'),
        ),
        migrations.AlterUniqueTogether(
            name='productsalepaymentsplit',
            unique_together={('product_sale', 'payment_method')},
        ),
    ]
