# Generated by Django 6.0.3 on 2026-04-02 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barber', '0001_initial'),
        ('barbershop', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('appointment_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('pendiente', 'Pendiente Confirmación'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_online_booking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='barber.barber')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='barbershop.barbershop')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'indexes': [models.Index(fields=['barbershop', 'appointment_datetime'], name='appointment_barbers_3acc54_idx'), models.Index(fields=['barber', 'appointment_datetime'], name='appointment_barber__ebf86a_idx')],
            },
        ),
    ]
