# Generated by Django 6.0.3 on 2026-04-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_datetime'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
    ]
