# Generated by Django 6.0.3 on 2026-05-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_b2_model_fixes'),
        ('barber', '0005_barber_barber_shop_active_idx_and_more'),
        ('barbershop', '0002_b2_model_fixes'),
        ('service', '0002_b2_model_fixes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['barbershop', 'status'], name='appt_shop_status_idx'),
        ),
    ]
