# Generated by Django 6.0.3 on 2026-04-02 01:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershop', '0001_initial'),
        ('payment_method', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto')),
                ('category', models.CharField(choices=[('compras', 'Compras / Insumos'), ('servicios', 'Servicios Externos'), ('mantenimiento', 'Mantenimiento'), ('nomina', 'Nomina / Personal'), ('arriendo', 'Arriendo'), ('publicidad', 'Publicidad'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Categoria')),
                ('detail', models.TextField(verbose_name='Detalle / descripcion')),
                ('expense_date', models.DateField(help_text='Fecha en que ocurrio el gasto', verbose_name='Fecha del gasto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='barbershop.barbershop')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='payment_method.paymentmethod', verbose_name='Metodo de pago')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
